version: '3'
services:
  db:
    image: unlie9/spa_service_postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    image: unlie9/spa_service_backend:latest
    ports:
      - "8002:8002"
    depends_on:
      - db
    env_file:
      - .env
    command: sh -c "./entrypoint.sh"

  daphne:
    image: unlie9/spa_service_daphne:latest
    ports:
      - "8003:8003"
    depends_on:
      - backend
      - redis
    env_file:
      - .env
    command: sh -c "daphne -p 8003 -b 0.0.0.0 comments_service.asgi:application"

  redis:
    image: unlie9/spa_service_redis:latest
    ports:
      - "6379:6379"

  frontend:
    image: unlie9/spa_service_frontend:latest
    depends_on:
      - backend
    ports:
      - "8080:8080"
    environment:
      - CHOKIDAR_USEPOLLING=true

  nginx:
    image: unlie9/spa_service_nginx:latest
    depends_on:
      - frontend
      - daphne
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

volumes:
  db_data:
