services:
  db:
    image: postgres:16.0-alpine3.17
    restart: always
    environment:
      - POSTGRES_DB=spa
      - POSTGRES_USER=spa_user
      - POSTGRES_PASSWORD=spa_password

    ports:
      - $POSTGRES_PORT:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    ports:
      - "8002:8002"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    env_file:
      - .env
    command: sh -c "./entrypoint.sh"

  daphne:
    build:
      context: ./backend
    ports:
      - "8003:8003"
    volumes:
      - ./backend:/app
    depends_on:
      - backend
      - redis
    env_file:
      - .env
    command: sh -c "daphne -p 8003 -b 0.0.0.0 comments_service.asgi:application"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    ports:
      - "8080:8080"
    environment:
      - CHOKIDAR_USEPOLLING=true

  nginx:
    image: nginx:latest
    depends_on:
      - frontend
      - daphne
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf


volumes:
  db_data:
