# Generated by Django 5.1.1 on 2024-10-13 14:16

import comments.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_alter_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=comments.utils.image_file),
        ),
    ]
